#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#   (1) You need a POSIX-compliant shell to run this script.
#   (2) You need to have java in PATH.
#
set -e

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

GRADLE_OPTS="${GRADLE_OPTS:-}"

# Determine the Java command to use.
if [ -n "$JAVA_HOME" ]; then
  JAVACMD="$JAVA_HOME/bin/java"
  if [ ! -x "$JAVACMD" ]; then
    echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    exit 1
  fi
else
  JAVACMD="java"
  which java > /dev/null 2>&1 || { echo "ERROR: JAVA_HOME is not set and no 'java' command could be found."; exit 1; }
fi

# Resolve links.
PRG="$0"
while [ -h "$PRG" ]; do
  ls=$(ls -ld "$PRG")
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=$(dirname "$PRG")"/$link"
  fi
done
SAVED="$(pwd)"
cd "$(dirname "$PRG")/" || exit
APP_HOME="$(pwd -P)"
cd "$SAVED" || exit

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

exec "$JAVACMD" \
  -classpath "$CLASSPATH" \
  $GRADLE_OPTS \
  org.gradle.wrapper.GradleWrapperMain "$@"
